spring:
  profiles:
    include:
      - domain

  jwt:
    secretKey: amluc29sLXNwcmluZy1ib290LWludml0ZS1wcm9qZWN0LXR1dG9yaWFsLWp3dC1zZWNyZXQta2V5Cg==

redis:
  key:
    invite-prefix: invite
invite:
  url:
    expiration: 3600000 # 1000 * 60 * 60 = 1시간
  newUser:
    init-password: $2a$10$KBpUjQGbu//.6MSzsfKYEuMVtOpGEi89bnMk3PMb4D7qCDEgDldGu #00000000