### 그룹 생성
POST http://localhost:8080/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJob25nQGFiYy5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjg3NDk0MjM2LCJleHAiOjE2ODc0OTc4MzZ9.kKz8I-hgWRg3doQAdovsXrBU9HwzBhjLDn254klZc0A

{
  "groupName" : "testGroup"
}

### 초대 링크 생성 - 신규 회원
POST http://localhost:8080/groups/invite/new/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJob25nQGFiYy5jb20iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjg3NTE5NDcwLCJleHAiOjE2ODc1MjMwNzB9.EhP2Q3A5w42b2zSrX6ZyxObz6w9mLy74olTaoS4V1Q4

{
  "userEmail" : "new1@abc.com",
  "userName" : "new1",
  "phone" : "01012341234"
}